sprintdoc-farm:
  environment: sprintdoc-farm
  tags:
    - locally
  only:
    - live
  script:
    - fab deploy
    

cosmocode-farm:
  environment: cosmocode-farm
  tags:
    - locally
  only:
    - live
  script:
    - fab deploy